# Generated by Django 4.0.2 on 2022-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0003_subcategory_category_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.ManyToManyField(null=True, to='programmingLanguages.SubCategory'),
        ),
    ]
