# Generated by Django 4.0.2 on 2022-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0004_remove_category_cat_category_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.ManyToManyField(to='programmingLanguages.SubCategory'),
        ),
    ]
