# Generated by Django 4.0.2 on 2022-04-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0006_remove_category_cat_category_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programmingLanguages.category'),
        ),
    ]
