# Generated by Django 4.0.2 on 2022-04-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0008_remove_language_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programmingLanguages.subcategory'),
        ),
    ]
