# Generated by Django 4.0.2 on 2022-04-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0010_remove_language_cat_language_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='cat',
        ),
        migrations.AddField(
            model_name='language',
            name='category',
            field=models.ManyToManyField(blank=True, to='programmingLanguages.SubCategory'),
        ),
    ]
