# Generated by Django 4.0.4 on 2022-04-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0011_remove_language_cat_language_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='category',
            new_name='subcategory',
        ),
    ]
