# Generated by Django 4.0.4 on 2022-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0012_rename_category_language_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='lang',
            field=models.ManyToManyField(blank=True, to='programmingLanguages.language'),
        ),
    ]
