# Generated by Django 4.0.4 on 2022-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0013_remove_language_subcategory_subcategory_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='lang',
        ),
        migrations.AddField(
            model_name='language',
            name='subcat',
            field=models.ManyToManyField(to='programmingLanguages.subcategory'),
        ),
    ]
