# Generated by Django 4.0.4 on 2022-04-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0014_remove_subcategory_lang_language_subcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='subcat',
            new_name='subcategories',
        ),
    ]
