# Generated by Django 4.0.4 on 2022-04-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0015_rename_subcat_language_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
