# Generated by Django 4.0.4 on 2022-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0016_alter_language_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField(default='Введите текст статьи')),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
