# Generated by Django 4.0.4 on 2022-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0017_post_alter_language_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(null=True, upload_to='./static/programmingLanguages/images'),
        ),
    ]
