# Generated by Django 4.0.4 on 2022-04-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0019_alter_language_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Главная категория', 'verbose_name_plural': 'Главные категории'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['title'], 'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['cat_id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='language',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='language',
            name='subcategories',
            field=models.ManyToManyField(to='programmingLanguages.subcategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Введите текст статьи', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programmingLanguages.category', verbose_name='Главная категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
    ]
