# Generated by Django 4.0.4 on 2022-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0020_alter_category_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='URL_slug', max_length=100, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='URL_slug', max_length=100, verbose_name='URL'),
        ),
    ]
