# Generated by Django 4.0.4 on 2022-04-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0021_language_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
