# Generated by Django 4.0.4 on 2022-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0022_remove_language_slug_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='URL_slug', max_length=100, null=True, verbose_name='URL'),
        ),
    ]
