# Generated by Django 4.0.4 on 2022-04-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0024_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
