# Generated by Django 4.0.4 on 2022-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0026_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
