# Generated by Django 4.0.4 on 2022-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0027_alter_language_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='Введите текст статьи', verbose_name='Статья'),
        ),
    ]
