# Generated by Django 4.0.4 on 2022-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguages', '0029_alter_language_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
