version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: web-site-languages-test
    command: python /usr/src/lang_test/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/lang_test
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
